[package]
name = "odgi-ffi"
version = "1.0.0"
authors = ["Milan Langhendries founder@caelrith.com"]
edition = "2024"
description = "A safe, ergonomic Rust wrapper for the odgi pangenome graph tool."
license = "MIT"
repository = "https://github.com/caelrith/odgi-ffi"
readme = "README.md"
keywords = ["odgi", "pangenome", "graph", "ffi", "bioinformatics"]
categories = ["science", "api-bindings", "external-ffi-bindings"]

# This is the final, aggressive exclude list.
# It removes the massive 'deps' directory and other non-essentials.
exclude = [
    "vendor/odgi/.git",
    "vendor/odgi/.github/",
    "vendor/odgi/.gitignore",
    "vendor/odgi/docs/",
    "vendor/odgi/test/",
    "vendor/odgi/examples/",
    "vendor/odgi/Dockerfile",
    
    # The MOST IMPORTANT line:
    "vendor/odgi/deps/",
]

[lib]
name = "odgi_ffi"
crate-type = ["rlib"]

[dependencies]
cxx = "1.0"
tempfile = "3.3.0"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
fs_extra = "1.3.0"

[dev-dependencies]

