[package]
name = "odgi-ffi"
version = "1.0.0"
authors = ["Milan Langhendries founder@caelrith.com"]
edition = "2024"
description = "A safe, ergonomic Rust wrapper for the odgi pangenome graph tool."
license = "MIT"
repository = "https://github.com/caelrith/odgi-ffi"
readme = "README.md"
keywords = ["odgi", "pangenome", "graph", "ffi", "bioinformatics"]
categories = ["science", "api-bindings", "external-ffi-bindings"]

# This is the final, definitive exclude list.
# The `**/` pattern is critical as it matches files and folders at ANY depth
# inside the submodule, which is where the bloat is hiding.
exclude = [
    # CRITICAL: Exclude all git version control data at any depth.
    "**/.git",
    "**/.github",
    "**/.gitignore",
    "**/.gitmodules",

    # Exclude documentation and tests at any depth.
    # We leave `examples` in as some build scripts might need them.
    "**/docs",
    "**/doc",
    "**/test",
    "**/tests",
    "**/testdata",

    # Exclude other non-essential files.
    "**/Dockerfile",
    "**/*.md",
    "!/README.md", # The `!` re-includes the main README file.
]

[lib]
name = "odgi_ffi"
crate-type = ["rlib"]

[dependencies]
cxx = "1.0"
tempfile = "3.3.0"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
fs_extra = "1.3.0"

[dev-dependencies]

