[package]
name = "odgi-ffi"
version = "0.1.0"
edition = "2021"
description = "A safe, ergonomic Rust wrapper for the odgi pangenome graph tool."
license = "MIT"
repository = "https://github.com/your-username/odgi-ffi"

[lib]
name = "odgi_ffi"
# CORRECTED: "lib" is redundant with "rlib" and was causing the collision.
# We only need to specify the final artifact type we want.
crate-type = ["rlib"]

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"

[dev-dependencies]
tempfile = "3.3.0"