[package]
name = "odgi-ffi"
version = "0.1.0"
# ADD an authors field
authors = ["Milan Langhendries founder@caelrith.com"]
edition = "2021"
description = "A safe, ergonomic Rust wrapper for the odgi pangenome graph tool."
license = "MIT"
repository = "https://github.com/your-username/odgi-ffi" # Don't forget to update "your-username"!

# ADD these fields for better discoverability and presentation
readme = "README.md"
keywords = ["odgi", "pangenome", "graph", "ffi", "bioinformatics"]
categories = ["science", "api-bindings", "external-ffi-bindings"]

[lib]
name = "odgi_ffi"
crate-type = ["rlib"]

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
fs_extra = "1.3.0" 

[dev-dependencies]
tempfile = "3.3.0"