[package]
name = "odgi-ffi"
version = "1.0.0"
authors = ["Milan Langhendries founder@caelrith.com"]
edition = "2024"
description = "A safe, ergonomic Rust wrapper for the odgi pangenome graph tool."
license = "MIT"
repository = "https://github.com/caelrith/odgi-ffi"
readme = "README.md"
keywords = ["odgi", "pangenome", "graph", "ffi", "bioinformatics"]
categories = ["science", "api-bindings", "external-ffi-bindings"]

# This is the final, correct exclude list.
# It ONLY removes git version control data, which is the main source of bloat.
# It leaves all source code directories (`test`, `examples`, etc.) intact,
# which is required to prevent the CMake build from failing.
exclude = [
    # Exclude the main submodule's git history.
    "vendor/odgi/.git",
    # The `**/` pattern matches at any depth. This is the most critical rule.
    "vendor/odgi/deps/**/*.git", # Excludes ALL nested git repos in the dependencies.
]

[lib]
name = "odgi_ffi"
crate-type = ["rlib"]

[dependencies]
cxx = "1.0"
tempfile = "3.3.0"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
fs_extra = "1.3.0"

[dev-dependencies]

